### ISSUE TITLE
Executing at comands for ble scan

### ISSUE THREAD

**Issue by ghost** [emakefun/emakefun-nano-plus#1]
Hi.
HOw can i execute at+scan on a loop and retrieve response from scan? i wnat to make a device that continously makes ble scan and later do something with the result.
Thank you

**Comment by emakefun** [comment]
I original design just can use USB port can use "AT COMMD"
but i will  realizes this new feature on BLE BSP vserion V1.6

**Comment by ghost** [comment]
Nice to hear that. Please advice when new version is available. Thank you
