### ISSUE TITLE
BLE NANO switching slaves

### ISSUE THREAD

**Issue by Helsgone** [emakefun/emakefun-nano-plus#2]
Hello, I want to do a multi-connection with 3 ble nano. How can I make the master switch between 2 slaves?

**Comment by emakefun** [comment]
such as 
you need get two slaves ble-nano macaddr  by AT+MAC , if you got two macaddr is MAC1 MAC2 do as

AT+CON=MAC1
delay(xxx;
AT+DISCON
AT+CON=MAC2
delay();
